"""add volume alerts table

Revision ID: 2a584bf03f53
Revises: 0001
Create Date: 2026-06-27 21:38:28.833920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a584bf03f53'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('volume_alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('current_volume', sa.Integer(), nullable=False),
    sa.Column('average_volume', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('ratio', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_volume_alerts_symbol'), 'volume_alerts', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_volume_alerts_symbol'), table_name='volume_alerts')
    op.drop_table('volume_alerts')
    # ### end Alembic commands ###
