"""add turnover and change to stock_candles

Revision ID: ebb1fd136646
Revises: 6f56bcbaec2c
Create Date: 2026-07-05 03:41:24.155257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebb1fd136646'
down_revision: Union[str, None] = '6f56bcbaec2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_candles', sa.Column('turnover', sa.Numeric(precision=16, scale=2), nullable=False))
    op.add_column('stock_candles', sa.Column('change', sa.Numeric(precision=12, scale=4), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_candles', 'change')
    op.drop_column('stock_candles', 'turnover')
    # ### end Alembic commands ###
